#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CAPTURES_ROOT="${BENCH_CAPTURE_OUTPUT_ROOT:-$PWD/.bench-captures}"
DEFAULT_SESSIONS_ROOT="${PERF_SESSION_OUTPUT_ROOT:-$PWD/.perf-sessions}"
DEFAULT_OUTPUT="$SCRIPT_DIR/../catalog/papers/arxiv-findings.md"
CAPTURES_ROOT="$DEFAULT_CAPTURES_ROOT"
SESSIONS_ROOT="$DEFAULT_SESSIONS_ROOT"
OUTPUT_FILE="$DEFAULT_OUTPUT"

usage() {
  cat <<'EOF'
Usage:
  harvest_paper_findings.sh [--captures-root DIR] [--sessions-root DIR] [--output FILE]

Scans benchmark capture notes and session starter reports for the
"Paper-Ready Finding" section and writes an aggregated arXiv-friendly
findings bundle.
EOF
}

extract_field() {
  local field="$1"
  local file="$2"

  awk -v field="$field" '
    /^## Paper-Ready Finding$/ { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section {
      prefix="- " field ":"
      if (index($0, prefix) == 1) {
        value=substr($0, length(prefix) + 1)
        sub(/^[[:space:]]+/, "", value)
        print value
        exit
      }
    }
  ' "$file"
}

is_falsey() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    no|n|false|0|skip|skipped)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

while [ $# -gt 0 ]; do
  case "$1" in
    --captures-root)
      if [ $# -lt 2 ]; then
        echo "--captures-root requires a value" >&2
        exit 2
      fi
      CAPTURES_ROOT="$2"
      shift 2
      ;;
    --sessions-root)
      if [ $# -lt 2 ]; then
        echo "--sessions-root requires a value" >&2
        exit 2
      fi
      SESSIONS_ROOT="$2"
      shift 2
      ;;
    --output)
      if [ $# -lt 2 ]; then
        echo "--output requires a value" >&2
        exit 2
      fi
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  echo "# arXiv-Ready Findings Bundle"
  echo
  echo "Generated by \`scripts/harvest_paper_findings.sh\`."
  echo
  echo "Use these findings as draft-ready building blocks for a paper, technical report, or public writeup."
  echo
} > "$OUTPUT_FILE"

found_any=0

while IFS= read -r notes_file; do
  title="$(extract_field finding_title "$notes_file")"
  paper_candidate="$(extract_field paper_candidate "$notes_file")"

  if [ -z "$title" ]; then
    continue
  fi

  if [ -n "$paper_candidate" ] && is_falsey "$paper_candidate"; then
    continue
  fi

  claim="$(extract_field claim "$notes_file")"
  finding_type="$(extract_field finding_type "$notes_file")"
  novelty_class="$(extract_field novelty_class "$notes_file")"
  bottleneck_class="$(extract_field bottleneck_class "$notes_file")"
  intervention="$(extract_field intervention "$notes_file")"
  baseline_condition="$(extract_field baseline_condition "$notes_file")"
  improved_condition="$(extract_field improved_condition "$notes_file")"
  primary_metric="$(extract_field primary_metric "$notes_file")"
  effect_size="$(extract_field effect_size "$notes_file")"
  secondary_effects="$(extract_field secondary_effects "$notes_file")"
  mechanism="$(extract_field mechanism "$notes_file")"
  operating_region="$(extract_field operating_region "$notes_file")"
  prerequisites="$(extract_field prerequisites "$notes_file")"
  caveats="$(extract_field caveats "$notes_file")"
  reproducibility_artifacts="$(extract_field reproducibility_artifacts "$notes_file")"
  figure_or_table_suggestion="$(extract_field figure_or_table_suggestion "$notes_file")"

  timestamp="$(sed -n 's/^- timestamp_utc: //p' "$notes_file" | head -n 1)"
  label="$(sed -n 's/^- label: //p' "$notes_file" | head -n 1)"
  run_dir="$(dirname "$notes_file")"

  summary_sentence="In ${operating_region:-the measured workload}, ${intervention:-the intervention} changed ${primary_metric:-the primary metric} by ${effect_size:-an unrecorded amount} relative to ${baseline_condition:-the baseline}. Mechanistically, ${mechanism:-the causal explanation was not recorded}."

  {
    echo "## ${title}"
    echo
    echo "- timestamp_utc: ${timestamp:-unknown-time}"
    echo "- label: ${label:-none}"
    echo "- finding_type: ${finding_type:-unclassified}"
    echo "- novelty_class: ${novelty_class:-unclassified}"
    echo "- bottleneck_class: ${bottleneck_class:-unknown}"
    echo "- source_run: \`$run_dir\`"
    echo "- source_note: \`$notes_file\`"
    echo
    echo "### Claim"
    echo
    echo "${claim:-No claim recorded.}"
    echo
    echo "### Draft Summary"
    echo
    echo "$summary_sentence"
    echo
    echo "### Intervention"
    echo
    echo "- baseline_condition: ${baseline_condition:-}"
    echo "- improved_condition: ${improved_condition:-}"
    echo "- primary_metric: ${primary_metric:-}"
    echo "- effect_size: ${effect_size:-}"
    echo "- secondary_effects: ${secondary_effects:-}"
    echo
    echo "### Mechanism And Scope"
    echo
    echo "- mechanism: ${mechanism:-}"
    echo "- operating_region: ${operating_region:-}"
    echo "- prerequisites: ${prerequisites:-}"
    echo "- caveats: ${caveats:-}"
    echo
    echo "### Reproducibility"
    echo
    echo "- reproducibility_artifacts: ${reproducibility_artifacts:-$run_dir}"
    echo "- figure_or_table_suggestion: ${figure_or_table_suggestion:-}"
    echo
    echo "### Suggested Table Row"
    echo
    echo "| ${title} | ${intervention:-} | ${primary_metric:-} | ${effect_size:-} | ${operating_region:-} | ${caveats:-} |"
    echo
  } >> "$OUTPUT_FILE"

  found_any=1
done < <(
  {
    if [ -d "$CAPTURES_ROOT" ]; then
      find "$CAPTURES_ROOT" -type f -name notes.md
    fi
    if [ -d "$SESSIONS_ROOT" ]; then
      find "$SESSIONS_ROOT" -type f -name starter-report.md
    fi
  } | sort
)

if [ "$found_any" = "0" ]; then
  echo "No paper-ready findings harvested yet." >> "$OUTPUT_FILE"
fi

printf 'paper_findings=%s\n' "$(cd "$(dirname "$OUTPUT_FILE")" && pwd)/$(basename "$OUTPUT_FILE")"
