#!/usr/bin/env bash
set -euo pipefail

DEFAULT_CAPTURES_ROOT="${BENCH_CAPTURE_OUTPUT_ROOT:-$PWD/.bench-captures}"
DEFAULT_SESSIONS_ROOT="${PERF_SESSION_OUTPUT_ROOT:-$PWD/.perf-sessions}"
DEFAULT_OUTPUT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../feedback/environment-tuning-matrix.md"
CAPTURES_ROOT="$DEFAULT_CAPTURES_ROOT"
SESSIONS_ROOT="$DEFAULT_SESSIONS_ROOT"
OUTPUT_FILE="$DEFAULT_OUTPUT"

usage() {
  cat <<'EOF'
Usage:
  harvest_tuning_matrix.sh [--captures-root DIR] [--sessions-root DIR] [--output FILE]

Scans benchmark capture notes and session starter reports for the
"Environment-Specific Tuning Notes" section and writes an aggregated
environment tuning matrix.
EOF
}

extract_field() {
  local field="$1"
  local file="$2"

  awk -v field="$field" '
    /^## Environment-Specific Tuning Notes$/ { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section {
      prefix="- " field ":"
      if (index($0, prefix) == 1) {
        value=substr($0, length(prefix) + 1)
        sub(/^[[:space:]]+/, "", value)
        print value
        exit
      }
    }
  ' "$file"
}

while [ $# -gt 0 ]; do
  case "$1" in
    --captures-root)
      if [ $# -lt 2 ]; then
        echo "--captures-root requires a value" >&2
        exit 2
      fi
      CAPTURES_ROOT="$2"
      shift 2
      ;;
    --output)
      if [ $# -lt 2 ]; then
        echo "--output requires a value" >&2
        exit 2
      fi
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --sessions-root)
      if [ $# -lt 2 ]; then
        echo "--sessions-root requires a value" >&2
        exit 2
      fi
      SESSIONS_ROOT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  echo "# Environment Tuning Matrix"
  echo
  echo "Generated by \`scripts/harvest_tuning_matrix.sh\`."
  echo
} > "$OUTPUT_FILE"

if [ ! -d "$CAPTURES_ROOT" ] && [ ! -d "$SESSIONS_ROOT" ]; then
  echo "No capture directory found at \`$CAPTURES_ROOT\` and no session directory found at \`$SESSIONS_ROOT\`." >> "$OUTPUT_FILE"
  exit 0
fi

found_any=0

while IFS= read -r notes_file; do
  hardware="$(extract_field hardware_profile "$notes_file")"
  firmware="$(extract_field firmware_or_driver "$notes_file")"
  tuned="$(extract_field tuned_parameters "$notes_file")"
  best="$(extract_field best_region "$notes_file")"
  cliffs="$(extract_field cliff_points "$notes_file")"
  impact="$(extract_field impact_summary "$notes_file")"
  direction_type="$(extract_field direction_type "$notes_file")"
  principle="$(extract_field portable_principle "$notes_file")"
  portability="$(extract_field portability_notes "$notes_file")"

  if [ -z "$hardware" ] && [ -z "$firmware" ] && [ -z "$tuned" ] && [ -z "$best" ] && [ -z "$cliffs" ] && [ -z "$impact" ] && [ -z "$direction_type" ] && [ -z "$principle" ] && [ -z "$portability" ]; then
    continue
  fi

  found_any=1
  run_dir="$(dirname "$notes_file")"
  timestamp="$(sed -n 's/^- timestamp_utc: //p' "$notes_file" | head -n 1)"
  label="$(sed -n 's/^- label: //p' "$notes_file" | head -n 1)"

  {
    echo "## ${timestamp:-unknown-time} ${label:+($label)}"
    echo
    echo "- run_dir: \`$run_dir\`"
    if [ -n "$hardware" ]; then
      echo "- hardware_profile: $hardware"
    fi
    if [ -n "$firmware" ]; then
      echo "- firmware_or_driver: $firmware"
    fi
    if [ -n "$tuned" ]; then
      echo "- tuned_parameters: $tuned"
    fi
    if [ -n "$best" ]; then
      echo "- best_region: $best"
    fi
    if [ -n "$cliffs" ]; then
      echo "- cliff_points: $cliffs"
    fi
    if [ -n "$impact" ]; then
      echo "- impact_summary: $impact"
    fi
    if [ -n "$direction_type" ]; then
      echo "- direction_type: $direction_type"
    fi
    if [ -n "$principle" ]; then
      echo "- portable_principle: $principle"
    fi
    if [ -n "$portability" ]; then
      echo "- portability_notes: $portability"
    fi
    echo
  } >> "$OUTPUT_FILE"
done < <(
  {
    if [ -d "$CAPTURES_ROOT" ]; then
      find "$CAPTURES_ROOT" -type f -name notes.md
    fi
    if [ -d "$SESSIONS_ROOT" ]; then
      find "$SESSIONS_ROOT" -type f -name starter-report.md
    fi
  } | sort
)

if [ "$found_any" = "0" ]; then
  echo "No environment-specific tuning notes found." >> "$OUTPUT_FILE"
fi

printf 'matrix=%s\n' "$(cd "$(dirname "$OUTPUT_FILE")" && pwd)/$(basename "$OUTPUT_FILE")"
