#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CAPTURES_ROOT="${BENCH_CAPTURE_OUTPUT_ROOT:-$PWD/.bench-captures}"
DEFAULT_SESSIONS_ROOT="${PERF_SESSION_OUTPUT_ROOT:-$PWD/.perf-sessions}"
DEFAULT_OUTPUT="$SCRIPT_DIR/../feedback/skill-improvement-backlog.md"
CAPTURES_ROOT="$DEFAULT_CAPTURES_ROOT"
SESSIONS_ROOT="$DEFAULT_SESSIONS_ROOT"
OUTPUT_FILE="$DEFAULT_OUTPUT"

usage() {
  cat <<'EOF'
Usage:
  harvest_skill_feedback.sh [--captures-root DIR] [--sessions-root DIR] [--output FILE]

Scans benchmark capture notes and session starter reports for the "Skill
Feedback" section and writes an aggregated backlog of concrete
skill-improvement candidates.
EOF
}

extract_field() {
  local field="$1"
  local file="$2"

  awk -v field="$field" '
    /^## Skill Feedback$/ { in_section=1; next }
    in_section && /^## / { in_section=0 }
    in_section {
      prefix="- " field ":"
      if (index($0, prefix) == 1) {
        value=substr($0, length(prefix) + 1)
        sub(/^[[:space:]]+/, "", value)
        print value
        exit
      }
    }
  ' "$file"
}

while [ $# -gt 0 ]; do
  case "$1" in
    --captures-root)
      if [ $# -lt 2 ]; then
        echo "--captures-root requires a value" >&2
        exit 2
      fi
      CAPTURES_ROOT="$2"
      shift 2
      ;;
    --output)
      if [ $# -lt 2 ]; then
        echo "--output requires a value" >&2
        exit 2
      fi
      OUTPUT_FILE="$2"
      shift 2
      ;;
    --sessions-root)
      if [ $# -lt 2 ]; then
        echo "--sessions-root requires a value" >&2
        exit 2
      fi
      SESSIONS_ROOT="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

mkdir -p "$(dirname "$OUTPUT_FILE")"

{
  echo "# Skill Improvement Backlog"
  echo
  echo "Generated by \`scripts/harvest_skill_feedback.sh\`."
  echo
} > "$OUTPUT_FILE"

if [ ! -d "$CAPTURES_ROOT" ] && [ ! -d "$SESSIONS_ROOT" ]; then
  echo "No capture directory found at \`$CAPTURES_ROOT\` and no session directory found at \`$SESSIONS_ROOT\`." >> "$OUTPUT_FILE"
  exit 0
fi

found_any=0

while IFS= read -r notes_file; do
  guidance="$(extract_field guidance_that_helped "$notes_file")"
  missing="$(extract_field missing_guidance "$notes_file")"
  gap="$(extract_field tool_or_script_gap "$notes_file")"
  trigger="$(extract_field trigger_issue "$notes_file")"
  candidate="$(extract_field candidate_update "$notes_file")"

  if [ -z "$guidance" ] && [ -z "$missing" ] && [ -z "$gap" ] && [ -z "$trigger" ] && [ -z "$candidate" ]; then
    continue
  fi

  found_any=1
  run_dir="$(dirname "$notes_file")"
  timestamp="$(sed -n 's/^- timestamp_utc: //p' "$notes_file" | head -n 1)"
  label="$(sed -n 's/^- label: //p' "$notes_file" | head -n 1)"

  {
    echo "## ${timestamp:-unknown-time} ${label:+($label)}"
    echo
    echo "- run_dir: \`$run_dir\`"
    if [ -n "$guidance" ]; then
      echo "- guidance_that_helped: $guidance"
    fi
    if [ -n "$missing" ]; then
      echo "- missing_guidance: $missing"
    fi
    if [ -n "$gap" ]; then
      echo "- tool_or_script_gap: $gap"
    fi
    if [ -n "$trigger" ]; then
      echo "- trigger_issue: $trigger"
    fi
    if [ -n "$candidate" ]; then
      echo "- candidate_update: $candidate"
    fi
    echo
  } >> "$OUTPUT_FILE"
done < <(
  {
    if [ -d "$CAPTURES_ROOT" ]; then
      find "$CAPTURES_ROOT" -type f -name notes.md
    fi
    if [ -d "$SESSIONS_ROOT" ]; then
      find "$SESSIONS_ROOT" -type f -name starter-report.md
    fi
  } | sort
)

if [ "$found_any" = "0" ]; then
  echo "No skill feedback entries found." >> "$OUTPUT_FILE"
fi

printf 'backlog=%s\n' "$(cd "$(dirname "$OUTPUT_FILE")" && pwd)/$(basename "$OUTPUT_FILE")"
